name: DodoTidy
options:
  bundleIdPrefix: com.dodotidy
  deploymentTarget:
    macOS: "14.0"
  createIntermediateGroups: true
  xcodeVersion: "15.0"

settings:
  base:
    MARKETING_VERSION: "1.0.5"
    CURRENT_PROJECT_VERSION: "1"
    DEVELOPMENT_TEAM: ""
    CODE_SIGN_IDENTITY: "-"
    CODE_SIGN_STYLE: Manual
    ENABLE_HARDENED_RUNTIME: NO
    INFOPLIST_KEY_LSApplicationCategoryType: "public.app-category.utilities"
    INFOPLIST_KEY_NSMainStoryboardFile: ""
    INFOPLIST_KEY_LSUIElement: NO
    ARCHS: "arm64 x86_64"
    ONLY_ACTIVE_ARCH: NO

targets:
  DodoTidy:
    type: application
    platform: macOS
    sources:
      - path: DodoTidy
      - path: DodoTidy/Resources/Assets.xcassets
      - path: DodoTidy/Resources/en.lproj
      - path: DodoTidy/Resources/tr.lproj
      - path: DodoTidy/Resources/de.lproj
      - path: DodoTidy/Resources/fr.lproj
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.dodotidy.app
        INFOPLIST_KEY_CFBundleDisplayName: "DodoTidy"
        PRODUCT_NAME: DodoTidy
        SWIFT_EMIT_LOC_STRINGS: YES
        GENERATE_INFOPLIST_FILE: YES
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
